  # This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Center.delete_all
Center.create(name: 'CU', address: 'Tegucigalpa, Francisco Morazán')
Center.create(name: 'UNAH-VS', address: 'San Pedro Sula, Cortés')
Center.create(name: 'CURLA', address: 'Ceiba, Atántida')
Center.create(name: 'CURC', address: 'Comayagua, Comayagua')
Center.create(name: 'CURVA', address: 'Olanchito, Yoro')
Center.create(name: 'UNAH-TEC DANLÍ', address: 'Danlí, El Paraíso')
Center.create(name: 'CURLP', address: 'Choluteca, Choluteca')
Center.create(name: 'CUROC', address: 'Santa Rosa de Copán, Copán')
Center.create(name: 'CURNO', address: 'Juticalpa, Olancho')

Department.delete_all
Department.create(name: 'Matemáticas', center: Center.find_by_name('CU'))
Department.create(name: 'Matemáticas', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Matemáticas', center: Center.find_by_name('CURLA'))
Department.create(name: 'Matemáticas', center: Center.find_by_name('CURC'))
Department.create(name: 'Matemáticas', center: Center.find_by_name('CURVA'))
Department.create(name: 'Matemáticas', center: Center.find_by_name('NAH-TEC DANLÍ'))
Department.create(name: 'Matemáticas', center: Center.find_by_name('CURLP'))
Department.create(name: 'Matemáticas', center: Center.find_by_name('CUROC'))
Department.create(name: 'Matemáticas', center: Center.find_by_name('CURNO'))
Department.create(name: 'Odontología', center:Center.find_by_name('CU'))
Department.create(name: 'Nutrición', center: Center.find_by_name('CU'))
Department.create(name: 'Ingeniería Industrial', center: Center.find_by_name('CU'))
Department.create(name: 'Ingeniería Mecánica', center: Center.find_by_name('CU'))
Department.create(name: 'Ingeniería en Sistemas', center: Center.find_by_name('CU'))
Department.create(name: 'Ingeniería Química', center: Center.find_by_name('CU'))
Department.create(name: 'Bancas y finanzas', center: Center.find_by_name('CU'))
Department.create(name: 'Psicología', center: Center.find_by_name('CU'))
Department.create(name: 'Biología', center: Center.find_by_name('CU'))
Department.create(name: 'Lenguas Extranjeras', center: Center.find_by_name('CU'))
Department.create(name: 'Letras', center: Center.find_by_name('CU'))
Department.create(name: 'Historia', center: Center.find_by_name('CU'))
Department.create(name: 'Filosofía', center: Center.find_by_name('CU'))
Department.create(name: 'Enfermería', center: Center.find_by_name('CU'))
Department.create(name: 'Física', center: Center.find_by_name('CU'))
Department.create(name: 'Periodismo', center: Center.find_by_name('CU'))
Department.create(name: 'Medicina', center: Center.find_by_name('CU'))
Department.create(name: 'Odontología', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Nutrición', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Ingeniería Industrial', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Ingeniería Mecánica', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Ingeniería en Sistemas', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Ingeniería Química', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Bancas y finanzas', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Psicología', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Biología', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Lenguas Extranjeras', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Letras', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Historia', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Filosofía', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Enfermería', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Física', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Periodismo', center: Center.find_by_name('UNAH-VS'))
Department.create(name: 'Medicina', center: Center.find_by_name('UNAH-VS'))

Resource.delete_all
Resource.create(name: 'Datashow')
Resource.create(name: 'Proyector')
Resource.create(name: 'Micrófono')
Resource.create(name: 'Laptop')
Resource.create(name: 'Equipo de sonido')
Resource.create(name: 'Ethernet')
Resource.create(name: 'Wi-fi')
Resource.create(name: 'Pantalla')

Admin.delete_all
Admin.create(name: 'Kevin', last_name: 'Maradiaga', email: 'Maradiaga.Kevin@unah.edu.hn', telephone: '22333450', password: 'Eipi+1=0', center: Center.find_by_name('CU'))
Admin.create(name: 'Kenny', last_name: 'Orellana', email: 'Orellana.Kenny@unah.edu.hn', telephone: '22333450', password: 'Eipi+1=0', center: Center.find_by_name('CU'))
Admin.create(name: 'Jasmin', last_name: 'Moreno', email: 'Moreno.Jasmin@unah.edu.hn', telephone: '22333450', password: 'Eipi+1=0', center: Center.find_by_name('CU'))
Admin.create(name: 'Henry', last_name: 'Ocampo', email: 'Ocampo.Henry@unah.edu.hn', telephone: '22333450', password: 'Eipi+1=0', center: Center.find_by_name('CU'))
Admin.create(name: 'Jose', last_name: 'Flores', email: 'Flores.Jose@unah.edu.hn', telephone: '22333450', password: 'Eipi+1=0', center: Center.find_by_name('CU'))

Teacher.delete_all
Teacher.create(name: 'Juan', last_name: 'Hernandez',  email: 'Hernandez.Juan@unah.edu.hn', telephone: '24234544', password: '000000', department: Department.find_by(name: 'Historia', center: Center.find_by_name('CU')))